### PR TITLE
WIP: Add Reprap page

### PR DESCRIPTION
**Pull request by marianhlavac**
The pictures are annoying.

**TODO:** Export EDUX images

### CODE REVIEW

**Review by hroncok — CHANGES_REQUESTED** [review]
Pictures missing.

**Comment by marianhlavac** [comment]
I forgot to put WIP in PR title, sorry.

**Comment by hroncok** [comment]
Will download the images from Edux.

**Comment by hroncok** [comment]
https://owncloud.cesnet.cz/index.php/s/XpdvxGagtnTWpF9 (can be downloaded in bulk using the top right Download button)

**Comment by marianhlavac** [comment]
Replacing with another PR

**Pull request closed without merging**
