### PR TITLE
Add hlavam30 teacher page

### PR DESCRIPTION
**Pull request by marianhlavac**

### CODE REVIEW

**Comment by hroncok** [comment]
I'm afraid relative links from withing subdirectory are currently broken :( sorry about that, will try to fix it.

**Comment by marianhlavac** [comment]
Owww, that's a bummer :(

**Comment by hroncok** [comment]
Nevertheless, please fix linter issues and add page to g2e.py. You might want to coordinate with the other PR not to get conflicts. I'll workaround the link problem in the evening.

**Comment by marianhlavac** [comment]
Sure thing. I can add the link any time later.

**Comment by hroncok** [comment]
Just have it without the link and I can add it together with the fix.

BTW Here's the promised selfie:

**Comment by marianhlavac** [comment]
:D :D Thanks for making my day better.

**Review by syky27 — APPROVED** [review]

**Review by syky27 — DISMISSED** [review]
Make sure it passed linter

**Comment by hroncok** [comment]
I've resolved conflicts via github. Please rebase before merging or squash when merging.

**Comment by hroncok** [comment]
Will you make this before tomorrow?

**Comment by hroncok** [comment]
Since this is blocking me, I'm going to rebase it.

**Review by hroncok — APPROVED** [review]

**Pull request merged**
