### PR TITLE
Update g2a.py

### PR DESCRIPTION
**Pull request by Hanyman8**
Add teacher/hanusji8

### CODE REVIEW

**Comment by hroncok** [comment]
Could you please create a single pull request with both? Practice your git skills a bit ;)

**Comment by Hanyman8** [comment]
Okay, I'm a noob yet. Sorry :)

**Comment by hroncok** [comment]
Everybody was a noob some time. Don't worry and ping us on slack if you need help.

**Comment by Hanyman8** [comment]
Thank you :')

**Pull request closed without merging**
