### PR TITLE
Add link to B181A-OpenSCAD1-Assignment

### PR DESCRIPTION
**Pull request by hroncok**
Don't merge yet, the repo is private.
Just approve, so I can merge it Tuesday morning.

### CODE REVIEW

**Review by syky27 — APPROVED** [review]

**Review by Hanyman8 — APPROVED** [review]
This is OK, but B181A-OpenSCAD1-Assignment link is not working now. I don't know if it is feature or bug.

**Comment by hroncok** [comment]
A feature. You should be able to see it now.

**Comment by Hanyman8** [comment]
screenshot from 2018-10-08 16-21-40
This is loading for more than 8 minutes

**Comment by hroncok** [comment]
Yes. The repo has been created long time ago, you can close this. We need to report this to GitHub.

**Comment by hroncok** [comment]
https://github.com/education/classroom/issues/1636

**Review by marianhlavac — APPROVED** [review]

**Pull request merged**
