### PR TITLE
Supports: Add points and little tweaks

### PR DESCRIPTION
**Pull request by hroncok**
(Will sync to Edux manually once merged.)

### CODE REVIEW

**Review by Hanyman8 — COMMENTED** [review]
I still like ... Vánoce (hehe) ...

**Comment by hroncok** [comment]
Vánoce hehe is from summer semester.

**Review by Hanyman8 — APPROVED** [review]
Ok

**Comment by hroncok** [comment]
Synced to Edux.

**Comment by marianhlavac** [comment]
hehe

**Pull request merged**
