### PR TITLE
WIP: Rest of pages

### PR DESCRIPTION
**Pull request by marianhlavac**
- There are about 100MB of images. Don't we want to use GIT LFS or something?
- Also we should rename the `images` folder, as it doesn't contain only images

### CODE REVIEW

**Comment by syky27** [comment]
@mmajko Make it work without GIT LFS at first, than we could discuss how to optimise this.

**Comment by hroncok** [comment]
@mmajko if you could take it one thing at a time, I believe we can progress faster. Giant PRs are pain. I suggest first finish PR for the lining and than go lecture by lecture. That would allow others to improve stuff that's already merged rather than being blocked by this single bottleneck. Thanks.

**Comment by syky27** [comment]
@hroncok I and @mmajko  will get this sorted out somehow tomorrow, I will make sure, that there will not be any more blocking huge PRs

**Comment by syky27** [comment]
Closing this, upon previous conversation.

**Pull request closed without merging**
