### PR TITLE
Add Literature page

### PR DESCRIPTION
**Pull request by hroncok**
(The content needs some love.)

### CODE REVIEW

**Review by syky27 — DISMISSED** [review]

**Review by syky27 — DISMISSED** [review]

**Comment by syky27** [comment]
I am gonna squash this when CI finishes...

**Comment by hroncok** [comment]
Don't, I'll do a full rebase.

**Comment by syky27** [comment]
Ok, merge when ready.

**Comment by hroncok** [comment]
rebased, needs new review

**Review by syky27 — APPROVED** [review]

**Pull request merged**
