### PR TITLE
Add link to B181A-Slicing-Assignment

### PR DESCRIPTION
**Pull request by marianhlavac**
⚠️ #127 Needs to be merged first.

### CODE REVIEW

**Comment by hroncok** [comment]
Please rebase.

**Comment by marianhlavac** [comment]
Jesus, screw github and their rebasing instead of merging. FFS!

**Comment by marianhlavac** [comment]
Wait what, there is no need to rebase.

**Comment by hroncok** [comment]
This PR list 19 commits. I've made sure to merge 127 form command line, yet I guess the branches have diverged in the meantime.

**Comment by hroncok** [comment]
Oh, so the commits look ok, maybe it juts GitHub having a bad mood. I try to close and open.

**Comment by hroncok** [comment]
Reopened as https://github.com/3DprintFIT/BI-3DT/pull/129

**Pull request closed without merging**
