### PR TITLE
Added images for structured light

### PR DESCRIPTION
**Pull request by jakubprusa**

### CODE REVIEW

**Review by Sinewa — DISMISSED** [review]

**Comment by hroncok** [comment]
Sources? We are trying to [fight stolen images](https://github.com/3DprintFIT/BI-3DT/issues/14), we cannot afford to introduce more of them.

**Comment by jakubprusa** [comment]
I know, sources are in my thesis and will be added soon, I want just make it as hotfix before exercise.

**Review by syky27 — CHANGES_REQUESTED** [review]
Add image sources.

**Comment by syky27** [comment]
@3DprintFIT/teachers This seems to be approved, even-thought there are some sources missing, so  please add those @jakubprusa

**Comment by hroncok** [comment]
@jakubprusa This is here for ages. Please finish it.

**Comment by hroncok** [comment]
@jakubprusa Either finish this, or close it. Your lack of communication is horrible.

**Pull request closed without merging**
